### ISSUE TITLE
Copy YAML Path is not working on a specific YAML file maybe due to it size

### ISSUE THREAD

**Issue by kzawad1** [jnugh/vscode-yamlpath#5]
I have been using "Copy YAML Path" for several months and it has been great.

Today, I ran into a situation where it copied the first 4 characters of a key that I initially ran "Copy YAML Path" and now further "Copy YAML Path" calls do not work.  

Can you help resolve this?

**Comment by jnugh** [comment]
Hi @kzawad1 thanks for using my extension 😃  
Sorry for the late reply. I have been on vacation.

You mention the size of your file. Are you talking about the nesting level or very long key names? Would it be possible for you to share the yaml file that triggers this?

Also you say it does not work afterwards. So the context menu entry is still there, right? Does it change the clipboard content or is it just doing nothing?

Can you check if there is any output in the developer console ("Developer: Toggle Developer Tools" should open a window with a "Console" tab)?

**Comment by kzawad1** [comment]
@jnugh , I was looking at your extensions source code and it is 57 lines of TypeScript that uses libraries.  I am using this plugin on Ubuntu Linux and VS Code.  I'm noticing the Ubuntu 20.04 LTS has prompts what seems like at least once a week that asks me to update some libraries.  I am assuming that one update broke this plugin because of a library update and another resolved the problem.

The plugin didn't work for a week and now it is back to working fine again.

When it didn't work I tried all sort of thing like rebooting, reimporting the project, closing all the files, etc...

Thank you for following up.

**Comment by jnugh** [comment]
Great! Let me know if it happens again 😄
